WINDOW_WIDTH = 1920
WINDOW_HEIGHT = 1080
FULLSCREEN = True
WINDOW_SIZE = WINDOW_WIDTH, WINDOW_HEIGHT

ARENA_WIDTH = 2800
ARENA_HEIGHT = 2000
ARENA_SIZE = ARENA_WIDTH, ARENA_HEIGHT

FRAMERATE = 60

WALKING = 0
IDLE = 1
ROLLING = 2

RIGHT = 0
LEFT = 1

BREAD = 1
GUN = 2
SHURIKEN = 3
FIRE = 4
GATLING = 6

COOLDOWNS = {BREAD: 1, GUN: 0.45, SHURIKEN: 0.9, FIRE: 5, GATLING: 0.1}

VALID_MODES = (GUN,BREAD,SHURIKEN,FIRE,GATLING)

BACKGROUND = 0
FOREGROUND = 1