WINDOW_WIDTH = 1920
WINDOW_HEIGHT = 1080
FULLSCREEN = True
WINDOW_SIZE = WINDOW_WIDTH, WINDOW_HEIGHT

ARENA_WIDTH = 2800
ARENA_HEIGHT = 2000
ARENA_SIZE = ARENA_WIDTH, ARENA_HEIGHT

FRAMERATE = 60

WALKING = 0
IDLE = 1
ROLLING = 2

RIGHT = 0
LEFT = 1

BREAD = 1
GUN = 2
SHURIKEN = 3

COOLDOWNS = {BREAD: 1, GUN: 0.4, SHURIKEN: 0.75}

VALID_MODES = (GUN,BREAD,SHURIKEN)

BACKGROUND = 0
FOREGROUND = 1